### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by kylekatarnls** [krakenjs/kraken-devtools#43]
If I try to load the URL `/anything.anything)`, I get this error:
<pre>SyntaxError: Caught exception: Invalid regular expression: //(.*)\.anything:)$/: Unmatched ')'
SyntaxError: Caught exception: Invalid regular expression: //(.*)\.anything:)$/: Unmatched ')'
  at new RegExp (<anonymous>:null:null)
  at start (node_modules/kraken-devtools/lib/middleware.js:45:21)
  at fn (node_modules/kraken-devtools/node_modules/async/lib/async.js:582:34)
  at Object._onImmediate (node_modules/kraken-devtools/node_modules/async/lib/async.js:498:34)
  at processImmediate [as _immediateCallback] (timers.js:336:15)</pre>

I see the code:
<pre>ext = path.extname(req.path).replace('.', '\\.');
regex = new RegExp(dir + '/(.*)' + ext +'$', 'i');</pre>

Inject the URL (user input) in a RegExp is a very bad idea IMHO.

**Comment by grawk** [comment]
Hi @kylekatarnls,

I'm the new maintainer of kraken-devtools and sweeping through open issues and PRs. Could you please expand upon how you see the existing regex manifesting as a security issue?

There is another bug which looks like it would be fixed by a change to this same regex so would like to consider these together and find the right solution.

**Comment by jasisk** [comment]
Fixed by #38.

**Comment by kylekatarnls** [comment]
Hum, you could have taken my commit instead of re-code exactly the same regex few months later:
https://github.com/krakenjs/kraken-devtools/commit/e2fd396c6c6f8517c715a6708b55586013ba1826
It's just one line, but you know, if you don't respect the authorship, you will lose a lot of help from the community, it's some things like that that make an coder get involved or not.

**Comment by jasisk** [comment]
Hey @kylekatarnls,

That commit actually came from a different pull-request—#50—I just cleaned up the commit message. Merging in the commit from that one vs yours was a simple oversight. My apologies.

I'll pull your commit and re-author the one you linked to in order to remove the unnecessary escaping. That way, you'll both land a commit.

**Comment by jasisk** [comment]
@kylekatarnls ab02da0f1384a6aa840ed149798479bdef3e7824

**Comment by kylekatarnls** [comment]
Thx, I appreciate.

**Comment by jasisk** [comment]
De rien. :grinning:
